name: Build and deploy to S3
on:
  create:
    tags:
      - v*
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup repository env
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: "https://registry.npmjs.org"
        scope: '@filestack'
    - name: Install deps
      run: npm install
    - name: Build code
      run: npm run build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site to S3 bucket
      run: aws s3 cp ./dist/ s3://filestack-prd-usea1-picker-debug --recursive
